name: lasher_adani
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase Suite (Updated for compatibility)
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0    # ADDED: For uploading files

  # UI & Utility Packages
  cupertino_icons: ^1.0.6
  lottie: ^3.1.0
  intl: ^0.19.0
  pinput: ^3.0.1

  # Feature Packages
  image_picker: ^1.0.4       # ADDED: For picking images from camera/gallery
  geolocator: ^10.1.0        # ADDED: For GPS location (for attendance)


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/LOGO.png
    - assets/neon_ring.json

