// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHZyTXLPwd8IpQW0WneDg1f-L-Cx4XzIs',
    appId: '1:320857118361:web:5ba88faeec06fc2a608a08',
    messagingSenderId: '320857118361',
    projectId: 'lasher-adani',
    authDomain: 'lasher-adani.firebaseapp.com',
    storageBucket: 'lasher-adani.firebasestorage.app',
    measurementId: 'G-LQPD36J339',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpgiMXP3AVfSJtLRz9mQWUm9w0zrTVxd0',
    appId: '1:320857118361:android:84c266de73a325f2608a08',
    messagingSenderId: '320857118361',
    projectId: 'lasher-adani',
    storageBucket: 'lasher-adani.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgo3xdXscCcOIV368X_BxPOptB6q8W-1g',
    appId: '1:320857118361:ios:87a482df130c66bc608a08',
    messagingSenderId: '320857118361',
    projectId: 'lasher-adani',
    storageBucket: 'lasher-adani.firebasestorage.app',
    iosBundleId: 'com.example.lasherAdani',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgo3xdXscCcOIV368X_BxPOptB6q8W-1g',
    appId: '1:320857118361:ios:87a482df130c66bc608a08',
    messagingSenderId: '320857118361',
    projectId: 'lasher-adani',
    storageBucket: 'lasher-adani.firebasestorage.app',
    iosBundleId: 'com.example.lasherAdani',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHZyTXLPwd8IpQW0WneDg1f-L-Cx4XzIs',
    appId: '1:320857118361:web:bd136b2cb3ac5153608a08',
    messagingSenderId: '320857118361',
    projectId: 'lasher-adani',
    authDomain: 'lasher-adani.firebaseapp.com',
    storageBucket: 'lasher-adani.firebasestorage.app',
    measurementId: 'G-Z1NDFEEK4G',
  );
}
